name: CI

on:
  # Will run on all PR's and pushes to master
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Build test
        run: |
          make setup
          make all

      - name: Run formatting check
        run: bash scripts/check_format.sh
        
      - name: Run linting check
        run: make lint

